import { createFileRoute } from '@tanstack/react-router';
import { AlertTriangle, BatteryCharging, CloudSun, Gauge } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { PageHeader, SectionTitle } from '@/components/firn/shell';
import { useFirn } from '@/lib/firn-context';
import { forecastData } from '@/lib/firn-data';
export const Route = createFileRoute('/forecast')({ head: () => ({ meta: [{ title: 'Forecast & Risk — FIRN' }, { name: 'description', content: 'Simulated renewable generation, demand and battery forecasts for polar station planning.' }, { property: 'og:title', content: 'Forecast & Risk — FIRN' }, { property: 'og:description', content: 'Explore FIRN’s simulated weather and energy forecast risk.' }, { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary_large_image' }] }), component: Forecast });
function Forecast() { const { scenarioId } = useFirn(); const data = forecastData.map(d => scenarioId === 'storm' && Number(d.time.slice(0,2)) >= 14 && Number(d.time.slice(0,2)) <= 20 ? {...d, renewable: Math.round(d.renewable*.55), battery: d.battery-10} : d); return <><PageHeader eyebrow="Predictive intelligence / Next 24 hours" title="Forecast & Risk" description="Weather Risk and resource availability shape when missions can run safely."/><div className="grid gap-5 xl:grid-cols-2"><ForecastChart title="Renewable Generation Forecast" metric="renewable" unit="kW" color="var(--primary)" icon={<CloudSun size={18}/>} data={data}/><ForecastChart title="Station Demand Forecast" metric="demand" unit="kW" color="var(--success)" icon={<Gauge size={18}/>} data={data}/><div className="xl:col-span-2"><ForecastChart title="Battery SOC Forecast" metric="battery" unit="%" color="var(--warning)" icon={<BatteryCharging size={18}/>} data={data}/></div></div><div className="mt-5 grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><div className="panel p-5 md:p-6"><SectionTitle>Forecast Confidence</SectionTitle><div className="grid gap-4 sm:grid-cols-3">{[['Renewable',82],['Demand',91],['Weather',76]].map(([label,value]) => <div key={label}><div className="flex justify-between text-xs"><span>{label}</span><span className="font-bold text-primary">{value}%</span></div><div className="mt-2 h-1.5 rounded-full bg-secondary"><div className="h-1.5 rounded-full bg-primary" style={{width:`${value}%`}}/></div></div>)}</div></div><div className="panel border-warning/30 bg-warning/5 p-5 md:p-6"><div className="flex items-center gap-2 text-sm font-bold"><AlertTriangle size={17} className="text-warning"/> Upcoming Risk</div><p className="mt-3 text-xs leading-5 text-muted-foreground">Renewable generation expected to decline between 14:00–20:00 due to worsening weather conditions.</p></div></div></>; }
function ForecastChart({title,metric,unit,color,icon,data}: {title:string;metric:'renewable'|'demand'|'battery';unit:string;color:string;icon:React.ReactNode;data:typeof forecastData}) { return <div className="panel min-w-0 p-5 md:p-6"><div className="flex items-center justify-between gap-2"><div className="flex items-center gap-2 font-display text-sm font-bold"><span className="text-primary">{icon}</span>{title}</div><span className="micro-label">NEXT 24H</span></div><div className="mt-6 h-[225px] w-full"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{top:5,right:5,left:-20,bottom:0}}><defs><linearGradient id={`fill-${metric}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={color} stopOpacity={.3}/><stop offset="100%" stopColor={color} stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 5"/><XAxis dataKey="time" tick={{fill:'var(--muted-foreground)',fontSize:10}} axisLine={false} tickLine={false} interval={2}/><YAxis tick={{fill:'var(--muted-foreground)',fontSize:10}} axisLine={false} tickLine={false} domain={metric==='battery'?[0,100]:[0,'auto']}/><Tooltip contentStyle={{background:'var(--popover)',border:'1px solid var(--border)',borderRadius:6,color:'var(--foreground)',fontSize:12}} formatter={(value) => [`${value} ${unit}`,title]} labelFormatter={(label) => `${label} · simulated`}/><Area type="monotone" dataKey={metric} stroke={color} strokeWidth={2} fill={`url(#fill-${metric})`} activeDot={{r:5}}/></AreaChart></ResponsiveContainer></div><div className="mt-2 text-right text-[10px] text-muted-foreground">Time (UTC) →</div></div>; }
