import { createFileRoute } from '@tanstack/react-router';
import { ArrowRight, CalendarClock, Check, Clock3, LoaderCircle, ShieldCheck, Sparkles, Zap } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { PageHeader, ReasonButton, SectionTitle, StatusBadge } from '@/components/firn/shell';
import { useFirn } from '@/lib/firn-context';
import { missionData } from '@/lib/firn-data';

export const Route = createFileRoute('/mission-planner')({ head: () => ({ meta: [{ title: 'Mission Planner — FIRN' }, { name: 'description', content: 'Simulated mission scheduling aligned with energy availability, deadlines and asset constraints.' }, { property: 'og:title', content: 'Mission Planner — FIRN' }, { property: 'og:description', content: 'Explore mission-aware and energy-aware scheduling for a polar station.' }, { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary_large_image' }] }), component: Planner });
const stages = ['Evaluating missions...', 'Checking asset availability...', 'Evaluating forecast risk...', 'Optimizing energy allocation...', 'Plan generated.'];
function Planner() { const { scenarioId, planGenerated, setPlanGenerated } = useFirn(); const [stage,setStage] = useState(-1);
 useEffect(() => { if(stage < 0 || stage >= 4) return; const timer = window.setTimeout(() => setStage(stage + 1), 240); return () => window.clearTimeout(timer); },[stage]);
 function generate() { setPlanGenerated(false); setStage(0); window.setTimeout(() => setPlanGenerated(true), 1200); }
 return <><PageHeader eyebrow="Planning / Science + Operations" title="Mission Planner" description="Schedule scientific and operational activities according to energy availability, deadlines and priorities." action={<Button onClick={generate} disabled={stage >= 0 && stage < 4}><Sparkles size={15}/>{stage >= 0 && stage < 4 ? 'Generating plan' : 'Generate Optimal Plan'}</Button>}/>
 <div className="mb-5 flex flex-wrap items-center gap-2 rounded-md border border-primary/20 bg-primary/5 p-4 text-xs text-muted-foreground"><span className="font-semibold text-primary">Mission-Aware</span><ArrowRight size={13}/><span className="font-semibold text-primary">Asset-Aware</span><ArrowRight size={13}/><span className="font-semibold text-primary">Energy-Aware</span><ArrowRight size={13}/><span className="font-semibold text-foreground">Joint Optimization</span></div>
 {stage >= 0 && <div className="panel mb-5 flex items-center gap-3 p-4" aria-live="polite">{stage < 4 ? <LoaderCircle size={19} className="animate-spin text-primary"/> : <Check size={19} className="text-success"/>}<div><div className="text-sm font-semibold">{stages[stage]}</div><p className="text-[11px] text-muted-foreground">{stage < 4 ? 'Balancing station priorities with available resources' : 'Adaptive Operating Plan ready · simulated optimization'}</p></div></div>}
 {planGenerated && <div className="panel mb-5 border-success/30 bg-success/5 p-5"><div className="flex items-center gap-2 text-sm font-bold text-success"><ShieldCheck size={17}/> Optimized schedule generated</div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{[['09:00','Experiment A','Renewable peak'],['13:00','Sample Processing','High priority'],['16:00','Water Production','Protected load'],[scenarioId === 'storm' ? '20:00' : '14:00','Experiment B',scenarioId === 'storm' ? 'Deferred 6 hours' : 'Flexible window']].map(([time,name,note]) => <div key={name} className="rounded border border-border bg-background/40 p-3"><div className="micro-label text-primary">{time}</div><div className="mt-1 text-sm font-semibold">{name}</div><div className="mt-1 text-[11px] text-muted-foreground">{note}</div></div>)}</div></div>}
 <SectionTitle aside={`${missionData.length} missions · simulated planning inputs`}>Mission queue</SectionTitle><div className="grid gap-4 lg:grid-cols-2">{missionData.map((m,i) => <div key={m.name} className="panel p-5 transition-colors hover:border-primary/40"><div className="flex items-start justify-between gap-3"><div><div className="micro-label">MISSION 0{i+1} / {m.priority} PRIORITY</div><h2 className="mt-2 font-display text-lg font-bold">{m.name}</h2></div><StatusBadge tone={m.priority === 'CRITICAL' ? 'warn' : m.status === 'RUNNING' ? 'good' : 'neutral'}>{scenarioId !== 'normal' && m.name === 'Experiment B' ? 'DEFERRED' : m.status}</StatusBadge></div><div className="mt-5 grid grid-cols-2 gap-x-4 gap-y-4 border-y border-border py-4 sm:grid-cols-4"><Detail icon={<Zap size={14}/>} label="POWER" value={m.power}/><Detail icon={<Clock3 size={14}/>} label="DURATION" value={m.duration}/><Detail icon={<CalendarClock size={14}/>} label="DEADLINE" value={m.deadline}/><Detail label="WEATHER" value={m.weather}/></div><div className="mt-4 grid gap-2 text-xs sm:grid-cols-2"><div><span className="text-muted-foreground">Equipment</span><span className="ml-2 font-medium">{m.equipment}</span></div><div><span className="text-muted-foreground">Interruptible</span><span className="ml-2 font-medium">{m.interruptible}</span></div></div><div className="mt-4 flex items-start gap-2 rounded border border-primary/20 bg-primary/5 p-3 text-xs"><Sparkles size={14} className="mt-0.5 shrink-0 text-primary"/><span><span className="font-semibold text-primary">FIRN recommendation · </span>{scenarioId !== 'normal' && m.name === 'Experiment B' ? 'Defer until renewable availability improves' : m.recommendation}</span></div></div>)}</div><div className="mt-5"><ReasonButton/></div></>;
}
function Detail({icon,label,value}: {icon?:React.ReactNode;label:string;value:string}) { return <div className="min-w-0"><div className="micro-label flex items-center gap-1">{icon}{label}</div><div className="mt-1.5 text-xs font-semibold">{value}</div></div>; }
