import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowDownRight, ArrowRight, BatteryCharging, CircleAlert, CloudSnow, Fuel, ShieldCheck, Wind, Zap } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PageHeader, ReasonButton, ScenarioChip, SectionTitle, StatusBadge } from '@/components/firn/shell';
import { useFirn } from '@/lib/firn-context';
import type { ScenarioId } from '@/lib/firn-data';

export const Route = createFileRoute('/scenario-simulator')({ head: () => ({ meta: [{ title: 'Scenario Simulator — FIRN' }, { name: 'description', content: 'Test simulated storms, asset failures, fuel delays and battery constraints in FIRN.' }, { property: 'og:title', content: 'Scenario Simulator — FIRN' }, { property: 'og:description', content: 'See how FIRN adapts polar missions and energy allocation together.' }, { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary_large_image' }] }), component: Simulator });
function Simulator() {
 const { scenario, scenarioId } = useFirn();
 const changed = scenarioId !== 'normal';
 const response = scenarioId === 'storm' ? [['Experiment A','MOVED EARLIER'],['Experiment B','DEFERRED'],['Sample Processing','RUN'],['Water Production','PROTECTED'],['Battery','RESERVE PROTECTED'],['Generator','READY'],['Fuel','CONSERVE']] : scenario.actions.map((a,i) => [[ 'Action 01','Action 02','Action 03','Action 04','Action 05'][i],a]);
 return <><PageHeader eyebrow="Operational intelligence / What-if analysis" title="Scenario Simulator" description="Test how FIRN adapts station operations to changing conditions." action={<span className="flex items-center gap-2 text-[11px] uppercase tracking-[.1em] text-muted-foreground"><span className="size-2 rounded-full bg-success dot-pulse"/> Simulation Mode</span>}/>
 <div className="panel mb-5 p-5 md:p-6"><div className="mb-4 flex items-center justify-between gap-3"><div><div className="micro-label text-primary">01 / Select a condition</div><h2 className="mt-1 font-display text-base font-bold">Station scenario</h2></div><div className="hidden text-[11px] text-muted-foreground md:block">Select a scenario to recalculate the operating plan</div></div><div className="flex flex-wrap gap-2">{(['normal','storm','generator','fuel','battery'] as ScenarioId[]).map(id => <ScenarioChip key={id} id={id}/>)}</div></div>
 <div className={`mb-5 flex flex-col gap-4 rounded-md border p-5 transition-colors md:flex-row md:items-center md:justify-between md:p-6 ${changed ? 'border-warning/35 bg-warning/5' : 'border-success/30 bg-success/5'}`}><div className="flex gap-3"><div className={`mt-0.5 ${changed ? 'text-warning' : 'text-success'}`}>{changed ? <CircleAlert size={23}/> : <ShieldCheck size={23}/>}</div><div><div className={`micro-label ${changed ? 'text-warning' : 'text-success'}`}>{changed ? 'Adaptive Replanning / FIRN response' : 'Normal conditions / operating plan'}</div><h2 className="mt-1 font-display text-xl font-bold">{scenario.headline}</h2><p className="mt-1 max-w-3xl text-xs leading-5 text-muted-foreground md:text-[13px]">{scenario.message}</p></div></div><StatusBadge tone={changed ? 'warn' : 'good'}>{changed ? 'PLAN ADAPTED' : 'PLAN STABLE'}</StatusBadge></div>
 <div className="mb-5 grid gap-5 xl:grid-cols-[.9fr_1.1fr]"><div className="panel p-5 md:p-6"><SectionTitle aside="Simulated station telemetry">Condition changes</SectionTitle><div className="grid grid-cols-2 gap-3">{[[CloudSnow,'TEMPERATURE',scenario.temperature,scenarioId === 'storm' ? '−3°C vs baseline' : 'Station exterior'],[Wind,'WIND SPEED',scenario.wind,scenarioId === 'storm' ? '+26 km/h vs baseline' : 'Within operating range'],[Zap,'RENEWABLES',`${scenario.solar + scenario.windPower} kW`,`${scenario.solar} solar + ${scenario.windPower} wind`],[BatteryCharging,'BATTERY SOC',`${scenario.battery}%`,scenarioId === 'battery' ? 'Usable capacity −30%' : 'Reserve threshold 30%']].map(([Icon,label,value,note]) => { const I = Icon as typeof Zap; return <div key={label as string} className="rounded border border-border bg-secondary/30 p-4"><I size={17} className="text-primary"/><div className="micro-label mt-3">{label as string}</div><div className="mt-1 font-display text-2xl font-bold">{value as string}</div><div className="mt-1 text-[11px] text-muted-foreground">{note as string}</div></div>; })}</div><div className="mt-3 grid grid-cols-2 gap-3"><div className="rounded border border-border bg-secondary/30 p-3"><div className="micro-label">Visibility / Weather Risk</div><div className="mt-1 text-sm font-semibold">{scenario.visibility} <span className="text-warning">· {scenario.risk}</span></div></div><div className="rounded border border-border bg-secondary/30 p-3"><div className="micro-label">Fuel reserve</div><div className="mt-1 flex items-center gap-2 text-sm font-semibold"><Fuel size={14} className="text-primary"/>{scenario.fuel}</div></div></div></div>
 <div className="panel border-primary/30 bg-primary/5 p-5 md:p-6"><div className="flex items-center justify-between gap-3"><div><div className="micro-label text-primary">02 / Joint Optimization</div><h2 className="mt-1 font-display text-lg font-bold">FIRN Response</h2></div><span className="text-[11px] text-muted-foreground">Mission + Energy + Assets</span></div><p className="mt-3 text-xs leading-5 text-muted-foreground">{changed ? 'FIRN balances mission priority, available assets, forecast risk and finite reserves to generate a revised plan.' : 'Current resources support scheduled science while maintaining critical load protection.'}</p><div className="mt-5 grid gap-2 sm:grid-cols-2">{changed ? response.map(([label,value]) => <div key={label} className="flex min-h-12 items-center justify-between gap-2 rounded border border-border bg-background/40 px-3 py-2"><span className="text-xs text-muted-foreground">{label}</span><span className="text-right text-[10px] font-bold uppercase text-primary">{value}</span></div>) : [['Experiment A','CONTINUE'],['Experiment B','SCHEDULED'],['Water Production','PROTECTED'],['Battery','RESERVE HEALTHY'],['Generator','STANDBY'],['Fuel','CONSERVE']].map(([label,value]) => <div key={label} className="flex min-h-12 items-center justify-between gap-2 rounded border border-border bg-background/40 px-3 py-2"><span className="text-xs text-muted-foreground">{label}</span><span className="text-[10px] font-bold text-success">{value}</span></div>)}</div><div className="mt-5"><ReasonButton/></div></div></div>
 <div className="panel p-5 md:p-6"><div className="flex flex-wrap items-center justify-between gap-2"><div><div className="micro-label text-primary">03 / Adaptive operating plan</div><h2 className="mt-1 font-display text-lg font-bold">Before / After FIRN Replan</h2></div><span className="text-[11px] text-muted-foreground">{changed ? scenario.label : 'Select a disruption to compare outcomes'}</span></div><div className="mt-5 grid items-stretch gap-3 md:grid-cols-[1fr_42px_1fr]"><Comparison title="BEFORE STORM" accent={false} rows={['Experiment A → 10:00','Experiment B → 14:00','Battery → 74%','Generator → Standby']}/><div className="flex items-center justify-center text-primary"><ArrowRight className="hidden md:block" size={23}/><ArrowDownRight className="md:hidden" size={23}/></div><Comparison title={changed ? 'AFTER FIRN REPLAN' : 'CURRENT OPERATING PLAN'} accent rows={changed ? scenarioId === 'storm' ? ['Experiment A → 09:00','Experiment B → Deferred 6 hrs','Battery → Reserve protected','Generator → Ready for critical loads'] : scenario.actions.slice(0,4) : ['Experiment A → 10:00','Experiment B → 14:00','Battery → 74%','Generator → Standby']}/></div><div className="mt-5 rounded border border-primary/20 bg-primary/5 p-4"><div className="flex items-center gap-2 text-xs font-bold"><ShieldCheck size={16} className="text-primary"/> Why did the plan change?</div><p className="mt-2 text-xs leading-5 text-muted-foreground">{scenarioId === 'storm' ? 'Expected renewable availability falls sharply during the storm window. FIRN shifts flexible missions, preserves battery reserve and keeps critical operations protected.' : changed ? scenario.message : 'No disruption is active. FIRN maintains the current mission schedule while monitoring forecast and reserve risk.'}</p></div></div>
 <div className="mt-5 flex flex-wrap items-center justify-between gap-3"><div className="micro-label">SENSE → PREDICT → OPTIMIZE → ADAPT → EXPLAIN</div><Button asChild variant="outline" className="bg-secondary/40"><Link to="/decision-log">View Decision Log <ArrowRight size={14}/></Link></Button></div></>;
}
function Comparison({title,accent,rows}: {title:string;accent:boolean;rows:string[]}) { return <div className={`rounded border p-4 md:p-5 ${accent ? 'border-primary/35 bg-primary/5' : 'border-border bg-secondary/25'}`}><div className={`micro-label ${accent ? 'text-primary' : ''}`}>{title}</div><div className="mt-4 space-y-3">{rows.map((row,i) => <div key={i} className="flex min-h-8 items-center border-b border-border/60 pb-2 text-xs last:border-0 last:pb-0">{row}</div>)}</div></div>; }
