import { Link, useRouterState } from '@tanstack/react-router';
import { Activity, ArrowUpRight, Bell, ChartNoAxesCombined, ChevronRight, CircleHelp, CloudSnow, Compass, Gauge, Hexagon, LayoutDashboard, Menu, Radio, ShieldCheck, SlidersHorizontal, X } from 'lucide-react';
import { useState, type ReactNode } from 'react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Toaster } from '@/components/ui/sonner';
import { useFirn } from '@/lib/firn-context';
import type { ScenarioId } from '@/lib/firn-data';

const nav = [
  { to: '/', label: 'Overview', icon: LayoutDashboard },
  { to: '/mission-planner', label: 'Mission Planner', icon: Compass },
  { to: '/energy-assets', label: 'Energy & Assets', icon: Gauge },
  { to: '/forecast', label: 'Forecast', icon: ChartNoAxesCombined },
  { to: '/scenario-simulator', label: 'Scenario Simulator', icon: SlidersHorizontal },
  { to: '/decision-log', label: 'Decision Log', icon: Activity },
] as const;

export function Shell({ children }: { children: ReactNode }) {
  const { scenario, scenarioId, reasoningOpen, setReasoningOpen } = useFirn();
  const [mobileOpen, setMobileOpen] = useState(false);
  const [noticesOpen, setNoticesOpen] = useState(false);
  const pathname = useRouterState({ select: s => s.location.pathname });
  return <div className="min-h-screen bg-background text-foreground lg:flex">
    {mobileOpen && <div className="fixed inset-0 z-30 bg-background/80 lg:hidden" onClick={() => setMobileOpen(false)} />}
    <aside className={`fixed inset-y-0 left-0 z-40 flex w-[244px] flex-col border-r border-border bg-sidebar transition-transform lg:sticky lg:top-0 lg:h-screen lg:translate-x-0 ${mobileOpen ? 'translate-x-0' : '-translate-x-full'}`}>
      <div className="flex h-[78px] items-center justify-between border-b border-border px-6">
        <Link to="/" className="flex items-center gap-3" onClick={() => setMobileOpen(false)}><div className="flex size-9 items-center justify-center rounded-md border border-primary/50 bg-primary/10 text-primary"><Hexagon size={21} strokeWidth={1.8}/></div><div><div className="font-display text-[24px] font-extrabold leading-none tracking-normal">FIRN<span className="text-primary">.</span></div><div className="mt-1 text-[9px] font-semibold uppercase tracking-[.21em] text-muted-foreground">Operational intelligence</div></div></Link>
        <Button variant="ghost" size="icon" className="lg:hidden" onClick={() => setMobileOpen(false)} aria-label="Close menu"><X/></Button>
      </div>
      <div className="px-5 pt-9"><div className="micro-label px-3">Workspace</div><nav className="mt-4 space-y-1">{nav.map(item => { const Icon = item.icon; const active = pathname === item.to; return <Link key={item.to} to={item.to} onClick={() => setMobileOpen(false)} className={`group flex h-11 items-center gap-3 rounded-md px-3 text-[13px] font-medium transition-colors ${active ? 'bg-primary/10 text-primary' : 'text-muted-foreground hover:bg-secondary hover:text-foreground'}`}><Icon size={17} strokeWidth={1.8}/><span>{item.label}</span>{active && <span className="ml-auto h-5 w-0.5 rounded-full bg-primary"/>}</Link>; })}</nav></div>
      <div className="mt-auto p-5"><div className="rounded-md border border-border bg-card/50 p-4"><div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-[.1em] text-success"><span className="size-1.5 rounded-full bg-success dot-pulse"/> System operational</div><div className="mt-2 text-[11px] text-muted-foreground">FIRN engine online</div><div className="mt-4 border-t border-border pt-3 text-[11px] text-muted-foreground">Simulation Mode <span className="float-right text-primary">●</span></div></div></div>
    </aside>
    <div className="min-w-0 flex-1"><header className="sticky top-0 z-20 flex h-[78px] items-center justify-between border-b border-border bg-background/95 px-5 backdrop-blur-xl md:px-8 xl:px-10">
      <div className="flex items-center gap-3"><Button variant="ghost" size="icon" className="lg:hidden" onClick={() => setMobileOpen(true)} aria-label="Open menu"><Menu/></Button><div className="flex size-8 items-center justify-center rounded-md border border-border bg-secondary text-primary"><Radio size={16}/></div><div><div className="font-display text-sm font-bold">Polar Station Alpha</div><div className="text-[11px] text-muted-foreground">Antarctic Research Network <span className="mx-1.5 text-border">/</span> Station 01</div></div></div>
      <div className="flex items-center gap-3 md:gap-5"><div className="hidden items-center gap-2 text-xs text-muted-foreground md:flex"><CloudSnow size={15} className="text-primary"/> {scenario.temperature} <span className="text-border">|</span> {scenario.wind}</div><div className="hidden h-7 w-px bg-border md:block"/><div className="hidden text-right text-[11px] leading-5 text-muted-foreground sm:block"><div className="font-semibold text-foreground">29 SEP 2026</div><div>08:42 UTC · SIMULATED</div></div><div className="relative"><Button variant="ghost" size="icon" aria-label="Notifications" onClick={() => setNoticesOpen(!noticesOpen)}><Bell size={18}/></Button>{noticesOpen && <div className="absolute right-0 top-12 z-30 w-72 rounded-md border border-border bg-popover p-4 shadow-xl"><div className="micro-label">Station notification</div><p className="mt-2 text-sm">{scenarioId === 'normal' ? 'Forecast Alert: storm probability increases over the next 8 hours.' : scenario.message}</p><Link to="/decision-log" onClick={() => setNoticesOpen(false)} className="mt-3 inline-flex items-center gap-1 text-xs text-primary">View Decision Log <ArrowUpRight size={13}/></Link></div>}</div><div className="flex size-8 items-center justify-center rounded-full border border-primary/40 bg-secondary text-xs font-bold text-primary" title="Station operator">OP</div></div>
    </header><main className="mx-auto max-w-[1600px] px-5 py-7 md:px-8 xl:px-10">{children}<footer className="mt-12 border-t border-border py-6 text-center text-[11px] text-muted-foreground">Simulation environment • Demonstration data • Not connected to live station infrastructure</footer></main></div>
    <Dialog open={reasoningOpen} onOpenChange={setReasoningOpen}><DialogContent className="max-h-[90vh] max-w-2xl overflow-y-auto bg-card p-7 text-foreground sm:p-9"><DialogHeader><div className="micro-label text-primary">Explainable Decisions / FIRN engine</div><DialogTitle className="mt-2 font-display text-2xl">Why did FIRN make this decision?</DialogTitle><DialogDescription>Joint Optimization considers missions, assets, energy, weather and fuel together.</DialogDescription></DialogHeader><div className="mt-5 rounded-md border border-primary/30 bg-primary/5 p-4"><div className="micro-label">Decision</div><div className="mt-2 text-lg font-semibold">{scenarioId === 'storm' ? 'Defer Experiment B by 6 hours' : scenarioId === 'normal' ? 'Maintain the current operating plan' : scenario.impact}</div></div><div className="mt-5 micro-label">Factors considered</div><div className="mt-2 grid gap-2 sm:grid-cols-2">{[['Weather Risk', scenarioId === 'storm' ? 'High storm probability' : scenario.risk + ' risk'], ['Renewable Energy', scenarioId === 'storm' ? 'Expected generation ↓ 42%' : `${scenario.solar + scenario.windPower} kW available`], ['Battery', 'Reserve protection required'], ['Fuel', 'Finite reserve · ' + scenario.fuel], ['Mission Priority', 'Experiment B = Medium'], ['Critical Operations', 'Heating + Water + Communications protected']].map(([label, value]) => <div key={label} className="rounded border border-border bg-secondary/40 p-3"><div className="micro-label">{label}</div><div className="mt-1 text-sm">{value}</div></div>)}</div><div className="mt-5 flex gap-3 rounded-md border border-success/30 bg-success/5 p-4"><ShieldCheck className="shrink-0 text-success" size={19}/><div><div className="micro-label text-success">Final action</div><p className="mt-1 text-sm">{scenarioId === 'storm' ? 'Defer Experiment B until renewable availability improves.' : scenario.actions[0] + '.'}</p></div></div><p className="mt-4 text-[11px] text-muted-foreground">Decision generated using simulated demonstration data.</p></DialogContent></Dialog>
    <Toaster position="bottom-right" theme="dark" richColors/>
  </div>;
}

export function PageHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: ReactNode }) { return <div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><div className="micro-label mb-2 text-primary">{eyebrow}</div><h1 className="font-display text-2xl font-bold md:text-[30px]">{title}</h1><p className="mt-1.5 max-w-2xl text-[13px] leading-relaxed text-muted-foreground">{description}</p></div>{action}</div>; }
export function SectionTitle({ children, aside }: { children: ReactNode; aside?: ReactNode }) { return <div className="mb-4 flex items-center justify-between gap-3"><h2 className="font-display text-[15px] font-bold">{children}</h2>{aside && <div className="text-xs text-muted-foreground">{aside}</div>}</div>; }
export function StatusBadge({ children, tone = 'neutral' }: { children: ReactNode; tone?: 'neutral' | 'good' | 'warn' | 'critical' }) { const colors = { neutral: 'bg-primary/10 text-primary border-primary/20', good: 'bg-success/10 text-success border-success/20', warn: 'bg-warning/10 text-warning border-warning/20', critical: 'bg-destructive/10 text-destructive border-destructive/20' }; return <span className={`inline-flex items-center whitespace-nowrap rounded border px-2 py-1 text-[10px] font-bold uppercase tracking-[.08em] ${colors[tone]}`}>{children}</span>; }
export function ReasonButton({ children = 'View Decision Reasoning' }: { children?: ReactNode }) { const { setReasoningOpen } = useFirn(); return <Button variant="outline" onClick={() => setReasoningOpen(true)} className="border-primary/30 bg-primary/5 text-primary hover:bg-primary/15 hover:text-primary">{children}<ChevronRight size={14}/></Button>; }
export function ScenarioChip({ id }: { id: ScenarioId }) { const { setScenario, scenarioId } = useFirn(); const labels: Record<ScenarioId,string> = { normal:'Normal Conditions',storm:'Severe Storm',generator:'Generator Failure',fuel:'Fuel Resupply Delay',battery:'Low Battery Capacity' }; return <Button variant={scenarioId === id ? 'default' : 'outline'} onClick={() => setScenario(id)} className={`h-auto min-h-10 whitespace-normal px-4 py-2 text-xs ${scenarioId === id ? '' : 'bg-secondary/50 text-muted-foreground hover:text-foreground'}`}>{labels[id]}</Button>; }
